name: CI

on:
  push: null
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 8.2
      run: |
        php -v | grep -q 8.2 && exit 0
        sudo apt install -y lsb-release gnupg2 ca-certificates apt-transport-https software-properties-common >/dev/null
        sudo add-apt-repository -y ppa:ondrej/php >/dev/null
        sudo apt install -y php8.2 php8.2-common php8.2-cli php8.2-curl php8.2-gd php8.2-intl php8.2-mbstring php8.2-sqlite3 php8.2-xml php8.2-zip php8.2-xdebug >/dev/null

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --quiet --prefer-dist --no-progress

    - name: Code Style (PHP Framework)
      run: composer run-script cs-dev

    - name: Tests Code Style
      run: composer run-script cs-tests

    - name: Static Analysis (PHP Framework)
      run: composer run-script analyze-dev

    - name: Tests Static Analysis 
      run: composer run-script analyze-tests
      
    - name: Tests (PHP Framework)
      run: env XDEBUG_MODE=coverage composer run-script test-dev

    - name: Javascript Standard
      run: composer run-script js-standard-dev
