name: Test Installs

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Run JS Standard
      run: |
        pwd
        ls -Alh ./
        ls -Alh ./Application/public/template/*/main
        npx standard ./Application/public/template/*/main
