name: Test Install php8.2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP 8.2
      run: |
        php -v | grep -q 8.2 && exit 0
        sudo apt install -y lsb-release gnupg2 ca-certificates apt-transport-https software-properties-common >/dev/null
        sudo add-apt-repository -y ppa:ondrej/php >/dev/null
        sudo apt install -y php8.2 php8.2-common php8.2-cli php8.2-curl php8.2-gd php8.2-intl php8.2-mbstring php8.2-sqlite3 php8.2-xml php8.2-zip >/dev/null
        php -v
        php -m

    - name: Install ESLint
      run: |
        npm install eslint@9.13.0
        npx eslint -v
