name: Test Install php8.2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP 8.2
      run: |
        php -v | grep -q 8.2 && exit 0
        echo EEEEEEEEEEEEEEEE
        
